#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill --no-fehbg ~/.st/backgrounds/archwave.png

bspc monitor -d 0 0 0 0 0 0 0
bspc config border_width         6
bspc config normal_border_color "#c0caf5"
bspc config active_border_color "#ff9e64"
bspc config focused_border_color "#f7768e"
bspc config window_gap          8
bspc config pointer_motion_interval 40

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Screenkey manage=off
bspc rule -a Peek state=floating follow=on
~/.config/polybar/launch.sh
pkill fcitx5 || fcitx5 &
